### PR TITLE
Save and load maps from files

### PR DESCRIPTION
**Pull request by victorreijgwart**

### CODE REVIEW

**Comment by victorreijgwart** [comment]
This PR was discussed in person instead of over GitHub, the main comments were:
* The packages are missing versions
* Too few comments
* Map->Stream and Stream->Map; why do some return values while others don't
* stream_conversions.cc
  * :102 Implications of using .emplace(...)
  * :143 Should mention C++17 requirements
  * :180 Should this return an error/raise an exception?
  * :194 Why shared_ptr?
  * :121, :226 code repetition
  * :283 continue behaves like a jump (unintuitive)
* wavemap_server.cc
  * :78 return False missing?

**Review by LionelOtt — APPROVED** [review]
Changes look good with future additions as discussed.

**Comment by victorreijgwart** [comment]
@LionelOtt Thank you for reviewing!

**Pull request merged**
